---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: win-2008r2
    driver:
      box: opentable/win-2008r2-standard-amd64-nocm

suites:
  - name: default
    run_list:
      - recipe[msi-maker::default]
    attributes:
