name 'msi-maker'
maintainer 'Salim Alam'
maintainer_email 'salam'
license 'Apache 2.0'
description 'Installs/Configures msi-maker'
long_description 'Installs/Configures msi-maker'
version '0.1.0'
